name: Deploy

on:
  workflow_run:
    workflows: [Release]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: GHCR_TOKEN
          script: |
            echo "$GHCR_TOKEN" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            cd ${{ vars.DEPLOY_PATH }}
            docker compose pull memory-pfl
            docker compose up -d memory-pfl
        env:
          GHCR_TOKEN: ${{ secrets.GH_PAT }}
